Adding more quality checks

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -44,13 +44,44 @@ jobs:
           poetry version $VERSION
 
       - name: Run ruff format check
+        continue-on-error: true
+        id: ruff-format
         run: poetry run ruff format --check --diff .
 
       - name: Run ruff lint check
+        continue-on-error: true
+        id: ruff-lint
         run: poetry run ruff check --diff .
 
+      - name: Run consistency checks between stub & module
+        continue-on-error: true
+        id: stubtest
+        env:
+          PYTHONPATH: "."
+        run: poetry run stubtest logprise
+
+      - name: Running mypy
+        continue-on-error: true
+        id: mypy
+        env:
+          PYTHONPATH: "."
+        run: poetry run mypy .
+
       - name: Run tests with coverage
+        continue-on-error: true
+        id: pytest
         run: poetry run pytest --cov=logprise --cov-report=xml
+
+      - name: Check if any quality check failed
+        if: |
+          steps.ruff-format.outcome == 'failure' ||
+          steps.ruff-lint.outcome == 'failure' ||
+          steps.stubtest.outcome == 'failure' ||
+          steps.mypy.outcome == 'failure' ||
+          steps.pytest.outcome == 'failure'
+        run: |
+          echo "At least one quality check failed"
+          exit 1
 
       - name: Upload coverage report
         uses: codecov/codecov-action@v5
